### ISSUE TITLE
Inconsistent:  URL Field in Behavior Section

### ISSUE THREAD

**Issue by dfirence** [mcafee-enterprise/ac3-threat-sightings#10]
The URL Field, is also inconsistently applied:  in TS_TA551, a behavior is set to string type, and in another behavior it is set to array type.  Schema Version `1.6` states it is supposed to be a `string` type when it is used in the `Behavior` section.

<br />

## Wiki Behavior Section

![image](https://user-images.githubusercontent.com/11415591/139558413-a81216b2-82c9-43cb-892e-85fb8b811bd3.png)

<br />
<br />

```json
          {
            "behavior": "MSHTA connected to public server via HTTP",
            "id": "68c2a8a7-cc23-4367-9001-2875b0ad08f4",
            "type": "Network Accessed",
            "connections": [
              {
                "dstIp": [
                  "45[.]144.29.211"
                ],
                "url": "http://wilkinstransportss[.]com/bdfh/M8vW0wEDKC/13990/98945/78577/UqmtFoUgSxQJgcBW2fbvUZ2w7h9ymtYJSptD/sumej1?m4m=uGAi7rUeR3HcNJNavdx&cid=LtbWPeO8zSCYlRGIYaA4Nf&H4PX=6Qrvk6oCdF49I89tjCSo&time=h9tCXQxzNuY1C4oJM4SS7q1cYDVUb",
                "dstHost": "wilkinstransportss[.]com",
                "protocol": "tcp",
                "dstPort": [
                  80
                ],
                "userAgent": [
                  "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)"
                ],
                "method": "GET"
              },
```

<br />
<br />

```yaml
    - behavior: MSHTA connected to public server via HTTP
      id: 68c2a8a7-cc23-4367-9001-2875b0ad08f4
      type: Network Accessed
      connections:
        - dstIp: 
          - 45[.]144.29.211
          url: http://wilkinstransportss[.]com/bdfh/M8vW0wEDKC/13990/98945/78577/UqmtFoUgSxQJgcBW2fbvUZ2w7h9ymtYJSptD/sumej1?m4m=uGAi7rUeR3HcNJNavdx&cid=LtbWPeO8zSCYlRGIYaA4Nf&H4PX=6Qrvk6oCdF49I89tjCSo&time=h9tCXQxzNuY1C4oJM4SS7q1cYDVUb
          dstHost: wilkinstransportss[.]com
          protocol: tcp
          dstPort: 
          - 80
          userAgent: 
          - "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)"
          method: GET
        - dstIp: 
          - 80[.]92.206.122
          dstHost: steptransport2017b[.]com
          protocol: tcp
          dstPort: 
          - 80
          userAgent: 
          - "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; HCTE; Zoom 3.6.0)"
          method: GET
      att&ck:
        commandAndControl:
        - "T1071.001 - Web Protocols"
```
