### ISSUE TITLE
Inconsistent: Integers vs Strings in Array of Network Objects

### ISSUE THREAD

**Issue by dfirence** [mcafee-enterprise/ac3-threat-sightings#11]
Schema version `1.6` states the network port objects are arrays of `string`, the Cobalt Strike Sighting has integers in the `Behavior` section.

<br />

![image](https://user-images.githubusercontent.com/11415591/139558802-ba9aede1-274c-4b7f-a741-0ce006ccee87.png)

<br />
<br />

```json
          {
            "behavior": "DLLHOST performed hundreds of network connections to local network",
            "id": "ced277c3-f68a-42b5-b153-55e1983d17ec",
            "type": "Network Accessed",
            "protocol": "tcp",
            "dstIp": [
              "#{PRIVATEIP}"
            ],
            "dstPort": [
              445
            ],
            "srcPort": [
              "#{high port number, eg. 63794}"
            ],
            "parentProcess": "C:\\\\Windows\\\\System32\\\\dllhost.exe",
            "att&ck": {
              "discovery": [
                "T1046 - Network Service Scanning"
              ]
            }
          },
```

<br />
<br />

```yaml
    - behavior: DLLHOST performed hundreds of network connections to local network
      id: ced277c3-f68a-42b5-b153-55e1983d17ec
      type: Network Accessed
      protocol: tcp
      dstIp:
      - '#{PRIVATEIP}'
      dstPort:
      - 445
      srcPort:
      - '#{high port number, eg. 63794}'
      parentProcess: C:\\Windows\\System32\\dllhost.exe
      att&ck:
        discovery:
        - "T1046 - Network Service Scanning"
```

<br />
<br />

## Inconsistency in TA551

In TA551 Sighting the `connections` array has network ports as integers. 

```yaml
    - behavior: MSHTA connected to public server via HTTP
      id: 68c2a8a7-cc23-4367-9001-2875b0ad08f4
      type: Network Accessed
      connections:
        - dstIp: 
          - 45[.]144.29.211
          url: http://wilkinstransportss[.]com/bdfh/M8vW0wEDKC/13990/98945/78577/UqmtFoUgSxQJgcBW2fbvUZ2w7h9ymtYJSptD/sumej1?m4m=uGAi7rUeR3HcNJNavdx&cid=LtbWPeO8zSCYlRGIYaA4Nf&H4PX=6Qrvk6oCdF49I89tjCSo&time=h9tCXQxzNuY1C4oJM4SS7q1cYDVUb
          dstHost: wilkinstransportss[.]com
          protocol: tcp
          dstPort: 
          - 80
          userAgent: 
          - "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)"
          method: GET
        - dstIp: 
          - 80[.]92.206.122
          dstHost: steptransport2017b[.]com
          protocol: tcp
          dstPort: 
          - 80
          userAgent: 
          - "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; HCTE; Zoom 3.6.0)"
          method: GET
```
