### ISSUE TITLE
Inconsistent:  Duplicate ParentProcess | Raccoon

### ISSUE THREAD

**Issue by dfirence** [mcafee-enterprise/ac3-threat-sightings#12]
### Inconsistent Schema

```text
Error: Message("duplicate field `parentProcess`", Some(Pos { marker: Marker { index: 23580, line: 430, col: 14 }, path: "threatSightings[7].observables[0]" }))
```

<br />
<br />

```yaml
    - behavior: Raccoon malware introduced a delayed command execution via CMD to delete itself
      type: Process Created
      id: 4c582288-580a-4cd1-9de3-460891e12643
      process: "C:\\Windows\\System32\\cmd.exe"
      parentProcess: "C:\\ProgramData\\IgHMwb34dcD\\door.exe"
      cmdLine:
      - 'cmd.exe /C timeout /T 10 /NOBREAK > Nul & Del /f /q "C:\\ProgramData\\IgHMwb34dcD\\door.exe"'
      - 'ping 1.1.1.1 -n 1 -w 3000 > Nul & Del /f /q "C:\\ProgramData\\IgHMwb34dcD\\door.exe"' #this IOC taken from other analysis
      parentProcess: "C:\\ProgramData\\IgHMwb34dcD\\door.exe"
      notes:
      - Via Timeout command a delay of 10 seconds is introduced.
      - Via ping command a delay of 3000 miliseconds is introduced.
      - Del is native cmd function for deleting files.
      att&ck:
        defenseEvasion:
        - "T1070.004 - Indicator Removal on Host: File Deletion"
        execution:
        - "T1059 - Command and Scripting Interpreter: Windows Command Shell"
```
