### ISSUE TITLE
Inconsistent:  Files Array

### ISSUE THREAD

**Issue by dfirence** [mcafee-enterprise/ac3-threat-sightings#9]
**Same as** #8 - Please apply consistent schema usage across sightings with version `1.6`, an array called `files` is proposed, its applied usage is broken.

In TA551:

```yaml
          {
            "behavior": "Weaponized .doc file created",
            "type": "File Created",
            "id": "97c18af0-e5de-48a8-a189-736983d7f2a7",
            "name": [
              "specifics 07.21.doc"
            ],
            "path": [
              "C:\\\\Users\\\\#{user}\\\\AppData\\\\Local\\\\Temp\\\\specifics 07.21.doc"
            ],
            "sha256": [
              "0092233b718257920a6bcbd333ab13558dbddf232bf3fde8387fe331644cecc3"
            ]
          }
```

<br />

```yaml
          {
            "behavior": "WINWORD dropped malicious HTA file at ProgramData folder",
            "id": "120b2efb-9325-4b70-825e-8313c9ccd3b9",
            "type": "File Created",
            "process": "C:\\Program Files\\Microsoft Office\\Office14\\WINWORD.EXE",
            "files": [
              {
                "path": "c:\\\\programdata\\\\brDefine.hta",
                "name": "brDefine.hta",
                "sha256": "2950bca9339171bacadce986114925b1392290bf85701f40350e9505e5da0bfb"
              },
              {
                "path": "C:\\\\ProgramData\\\\sds.hta",
                "name": "sds.hta",
                "sha256": "D62C9C87F14E3E762E5DA9A7D32679142DC0A5D91DDF8EB8C7A7B51B8343CF24"
              }
            ],
            "notes": [
              "during the execution of WINWORD, files were dropped."
            ],
            "parentProcess": "C:\\\\Program Files\\\\Microsoft Office\\\\Office14\\\\WINWORD.EXE"
          },
```

<br />

```yaml

          {
            "behavior": "WINWORD dropped malicious HTA file at ProgramData folder",
            "id": "120b2efb-9325-4b70-825e-8313c9ccd3b9",
            "type": "File Created",
            "process": "C:\\Program Files\\Microsoft Office\\Office14\\WINWORD.EXE",
            "files": [
              {
                "path": "c:\\\\programdata\\\\brDefine.hta",
                "name": "brDefine.hta",
                "sha256": "2950bca9339171bacadce986114925b1392290bf85701f40350e9505e5da0bfb"
              },
              {
                "path": "C:\\\\ProgramData\\\\sds.hta",
                "name": "sds.hta",
                "sha256": "D62C9C87F14E3E762E5DA9A7D32679142DC0A5D91DDF8EB8C7A7B51B8343CF24"
              }
            ],
            "notes": [
              "during the execution of WINWORD, files were dropped."
            ],
            "parentProcess": "C:\\\\Program Files\\\\Microsoft Office\\\\Office14\\\\WINWORD.EXE"
          },
```
